# application.yaml
spring:
  application:
    name: frontoffice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/frontoffice_db
    username: frontoffice_user
    password:
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      generate-dll: true
      show-sql: true

