# docker-compose.yaml
name: frontoffice
services:
  postgresql:
    image: postgres:17.4
    # volumes:
    #   - ~/Downloads/frontoffice/frontoffice_db/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=frontoffice_user
      - POSTGRES_DB=frontoffice_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
